<script type="text/javascript" src="${baseurl}/js/jquery-1.11.3.min.js"></script>
<script type="text/javascript" src="${baseurl}/js/jquery.tips.js"></script>
<script type="text/javascript" src="${baseurl}/js/handlerResultInfo.js"></script>
<script type="text/javascript" src="${baseurl}/js/popwin.js"></script>
<script type="text/javascript" src="${baseurl}/js/validateIDNumber.js"></script>
<script type="text/javascript" src="${baseurl}/js/jstree.min.js"></script>
<script type="text/javascript" src="${baseurl}/js/jquery.form.min.js"></script>
<script type="text/javascript" src="${baseurl}/js/dataTable/js/jquery.dataTables.min.js"></script>
<script type="text/javascript" src="${baseurl}/js/bootstrap/js/bootstrap.js"></script>
<script type="text/javascript" src="${baseurl}/js/laydate/laydate.js"></script>
<script type="text/javascript" src="${baseurl}/js/ckeditor/ckeditor.js"></script>
